apiVersion: v1
kind: ConfigMap
metadata:
  name: aqua-csp-enforcer
  namespace: aqua
data:
  AQUA_HEALTH_MONITOR_ENABLED: "true"
  AQUA_CLEAN_INSTALL: "true"
  AQUA_NETWORK_FAIL_MODE: "open"
  AQUA_INSTALL_PATH: "/var/lib/aquasec2"
  AQUA_MEMORY_PRESSURE: "critical"
  AQUA_SERVER: "aqua-gateway:8443" # this is replaced
  AQUA_LOGICAL_NAME: "" # this is replaced
  RESTART_CONTAINERS: "no"
  SILENT: "yes"
